package com.note.compose.ui.theme.datamodel

data class Tag(
    val id: String = "", // Autogenerated
    val tagName: String = ""
)

data class Note(
    var id: String = "", // Autogenerated
    val title: String = "",
    val description: String = "",
    val tag: String = ""
)

data class User(
    val id: String = "", // Autogenerated
    val userName: String = "",
    val email: String = "",
    val password: String = "",
    val notes: List<Note> = emptyList(),
    val tags: List<Tag> = emptyList()
)